### ISSUE TITLE
Server stopping bug

### ISSUE THREAD

**Issue by Kabongosalomon** [dsfsi/masakhane-web#54]
Investigate, why the production backend service stops from time to time.

**Comment by lastrucci01** [comment]
The full error message is quite lengthy...
<details>
<summary> Full Error </summary>
<p> packages.GetPackageUpdates() error: error getting apt updates: error running /usr/bin/apt-get with args ["update"]: exit status 100, stdout: "Get:1 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]\nGet:2 http://deb.debian.org/debian buster InRelease [122 kB]\nGet:3 https://nvidia.github.io/libnvidia-container/stable/debian10/amd64  InRelease [1484 B]\nGet:4 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]\nHit:5 https://nvidia.github.io/nvidia-container-runtime/stable/debian10/amd64  InRelease\nHit:6 https://nvidia.github.io/nvidia-docker/debian10/amd64  InRelease\nGet:7 https://download.docker.com/linux/debian buster InRelease [54.0 kB]\nGet:8 http://deb.debian.org/debian buster-backports InRelease [51.4 kB]\nGet:10 http://packages.cloud.google.com/apt cloud-sdk-buster InRelease [6396 B]\nGet:11 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-buster InRelease [5163 B]\nGet:9 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [8993 B]\nGet:12 http://packages.cloud.google.com/apt gcsfuse-buster InRelease [5004 B]\nGet:13 http://packages.cloud.google.com/apt google-compute-engine-buster-stable InRelease [5136 B]\nErr:10 http://packages.cloud.google.com/apt cloud-sdk-buster InRelease\n  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05\nErr:11 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-buster InRelease\n  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05\nErr:9 https://packages.cloud.google.com/apt kubernetes-xenial InRelease\n  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05\nErr:12 http://packages.cloud.google.com/apt gcsfuse-buster InRelease\n  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05\nErr:13 http://packages.cloud.google.com/apt google-compute-engine-buster-stable InRelease\n  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05\nReading package lists...\n", stderr: "E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'\nE: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'\nE: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'\nW: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/apt cloud-sdk-buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05\nW: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05\nW: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://packages.cloud.google.com/apt kubernetes-xenial InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05\nW: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/apt gcsfuse-buster InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05\nW: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.cloud.google.com/apt google-compute-engine-buster-stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05\n" </p>
</details>

What you will notice is the repition of: **NO_PUBKEY B53DC80D13EDEF05**

I followed [this article](https://chrisjean.com/fix-apt-get-update-the-following-signatures-couldnt-be-verified-because-the-public-key-is-not-available/) and sshed into the gcp instance and added a public key. 

I see it attempted the apt update again now and I am happy to report a _shorter_ error :))

<details>
<summary> Shorter Error </summary>
<p> packages.GetPackageUpdates() error: error getting apt updates: error running /usr/bin/apt-get with args ["update"]: exit status 100, stdout: "Get:1 http://security.debian.org/debian-security buster/updates InRelease [34.8 kB]\nGet:2 https://nvidia.github.io/libnvidia-container/stable/debian10/amd64  InRelease [1484 B]\nGet:3 https://download.docker.com/linux/debian buster InRelease [54.0 kB]\nHit:4 https://nvidia.github.io/nvidia-container-runtime/stable/debian10/amd64  InRelease\nHit:5 https://nvidia.github.io/nvidia-docker/debian10/amd64  InRelease\nGet:7 http://packages.cloud.google.com/apt cloud-sdk-buster InRelease [6396 B]\nGet:8 http://deb.debian.org/debian buster InRelease [122 kB]\nGet:9 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]\nHit:10 http://deb.debian.org/debian buster-backports InRelease\nGet:11 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-buster InRelease [5163 B]\nGet:6 https://packages.cloud.google.com/apt kubernetes-xenial InRelease [8993 B]\nGet:12 http://packages.cloud.google.com/apt gcsfuse-buster InRelease [5004 B]\nGet:13 http://packages.cloud.google.com/apt google-compute-engine-buster-stable InRelease [5136 B]\nGet:14 http://packages.cloud.google.com/apt cloud-sdk-buster/main amd64 Packages [396 kB]\nGet:15 http://packages.cloud.google.com/apt google-cloud-packages-archive-keyring-buster/main amd64 Packages [389 B]\nGet:16 https://packages.cloud.google.com/apt kubernetes-xenial/main amd64 Packages [63.2 kB]\nGet:17 http://packages.cloud.google.com/apt gcsfuse-buster/main amd64 Packages [1871 B]\nGet:18 http://packages.cloud.google.com/apt google-compute-engine-buster-stable/main amd64 Packages [2235 B]\nReading package lists...\n", stderr: "E: Repository 'http://security.debian.org/debian-security buster/updates InRelease' changed its 'Suite' value from 'stable' to 'oldstable'\nE: Repository 'http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'\nE: Repository 'http://deb.debian.org/debian buster-updates InRelease' changed its 'Suite' value from 'stable-updates' to 'oldstable-updates'\n" </p> 
</details>

Will provide further updates upon knocking down this error - something about "http://deb.debian.org/debian buster InRelease' changed its 'Suite' value from 'stable' to 'oldstable'"

**Comment by lastrucci01** [comment]
So with regards to my previous posts _shorter error_ I followed (this article)[https://stackoverflow.com/questions/68802802/repository-http-security-debian-org-debian-security-buster-updates-inrelease] and their recommendation is to change `sudo apt-get update` to `sudo apt-get --allow-releaseinfo-change update` resolves the issue. 

As such I ran that command on the instance and it has not thrown an error like it does every 10 minutes. 

Unfortunately (translate.masakhane.io)[http://translate.masakane.io/] is still down - I am thinking of rebooting the instance but that might not work as I will probably need to update the `sudo apt-get update` within the Dockerfile.prod

I am not that well versed running servers  on cloud instances so I am going to do some research on that regard. 
Will continue to update this thread :))
